#!/bin/bash
# MusicMind for Plex — Docker entrypoint
#
# Two real jobs, both idempotent (safe to run on every container
# start, not just the first):
#
#   1. Generate config.py from environment variables, if one doesn't
#      already exist. A user who mounts their own config.py directly
#      (matching the existing non-Docker workflow) is left alone
#      entirely — this only ever fills a genuine gap, never overwrites
#      something already there.
#
#   2. For the "full" variant only: download the VI model file if
#      it's not already present in the persistent /app/models volume.
#      Fetched directly from essentia.upf.edu (the original source),
#      never baked into the image itself — respects the same "link
#      don't bundle" principle already stated in .gitignore for this
#      CC BY-NC-SA licensed file.

set -e

DATA_DIR="/app/data"
MODELS_DIR="/app/models"
CONFIG_PATH="/app/config.py"

mkdir -p "$DATA_DIR" "$MODELS_DIR"

# --- Job 1: generate config.py from environment, if needed ---
if [ ! -f "$CONFIG_PATH" ]; then
    if [ -z "$PLEX_URL" ] || [ -z "$PLEX_TOKEN" ] || [ -z "$OPENAI_KEY" ]; then
        echo "============================================================"
        echo "MusicMind for Plex — first run, configuration required."
        echo "============================================================"
        echo "No config.py found, and required environment variables are"
        echo "not set. Provide these when running the container:"
        echo "  PLEX_URL       e.g. http://10.0.0.251:32400"
        echo "  PLEX_TOKEN     see the README for how to get this"
        echo "  OPENAI_KEY     sk-proj-..."
        echo
        echo "Optional:"
        echo "  MUSIC_LIB      Plex music library name (default: Music)"
        echo "  LASTFM_KEY, LASTFM_USER   leave unset to disable Last.fm"
        echo "  PATH_MAP_JSON  e.g. '{\"J:\\\\Music\": \"/mnt/j/Music\"}'"
        echo
        echo "Or mount your own pre-filled config.py directly to"
        echo "$CONFIG_PATH instead — see docker-compose.yml."
        echo "============================================================"
        exit 1
    fi

    echo "Generating config.py from environment variables..."

    python3 - "$CONFIG_PATH" << 'PYEOF'
import os, sys, json

path = sys.argv[1]

path_map = {}
raw_path_map = os.environ.get("PATH_MAP_JSON", "").strip()
if raw_path_map:
    try:
        path_map = json.loads(raw_path_map)
    except json.JSONDecodeError as e:
        print(f"WARNING: PATH_MAP_JSON is not valid JSON ({e}) — using an empty PATH_MAP instead.")
        path_map = {}

lines = [
    "# Auto-generated by docker-entrypoint.sh from environment variables.",
    "# Delete this file and mount your own to take manual control instead.",
    "import os",
    "BASE_DIR = os.path.dirname(os.path.abspath(__file__))",
    'DB_PATH = "/app/data/musicmind.db"',
    f'PLEX_URL = {os.environ["PLEX_URL"]!r}',
    f'PLEX_TOKEN = {os.environ["PLEX_TOKEN"]!r}',
    f'MUSIC_LIB = {os.environ.get("MUSIC_LIB", "Music")!r}',
    f'OPENAI_KEY = {os.environ["OPENAI_KEY"]!r}',
    f'LASTFM_KEY = {os.environ.get("LASTFM_KEY", "")!r}',
    f'LASTFM_USER = {os.environ.get("LASTFM_USER", "")!r}',
    f'PATH_MAP = {path_map!r}',
    "IS_MASTER = False",
]

with open(path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {path}")
PYEOF

    echo "config.py generated."
fi

# --- Job 2: download the VI model, full variant only ---
VI_MODEL_PATH="$MODELS_DIR/voice_instrumental-musicnn-msd-1.pb"
VI_MODEL_URL="https://essentia.upf.edu/models/classifiers/voice_instrumental/voice_instrumental-musicnn-msd-1.pb"

if [ "$MUSICMIND_VARIANT" = "full" ] && [ ! -f "$VI_MODEL_PATH" ]; then
    echo "Full variant, VI model not found — downloading from essentia.upf.edu..."
    if curl -fsSL "$VI_MODEL_URL" -o "$VI_MODEL_PATH.tmp"; then
        mv "$VI_MODEL_PATH.tmp" "$VI_MODEL_PATH"
        echo "VI model downloaded successfully."
    else
        echo "WARNING: VI model download failed — VI will be unavailable"
        echo "until this succeeds on a future restart. Synapse's core"
        echo "BPM/key/danceability measurement is unaffected."
        rm -f "$VI_MODEL_PATH.tmp"
    fi
fi

exec "$@"
